### ISSUE TITLE
no support for i686

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/precise-data#1]
i can not use precise in my system

`15:42:04.336 - urllib3.connectionpool - DEBUG - https://github.com:443 "GET /MycroftAI/precise-data/raw/dist/i686/latest HTTP/1.1" 404 None`

**Comment by MatthewScholefield** [comment]
Unfortunately, it would be too difficult to support 32 bit. Tensorflow doesn't have [prebuilt binaries](https://pypi.org/project/tensorflow/#files) for 32 bit machines and compiling tensorflow from source is a nightmare. However, you are welcome to perform a source install for Precise if you manage to get tensorflow working properly.
